branches:
  only:
    - main
    - v3.2.x

addons:
  apt:
    packages:
      - imagemagick

language: php

env:
  global:
    - PHAN_ALLOW_XDEBUG=0 PHAN_DISABLE_XDEBUG_WARN=1

matrix:
  include:
    - php: 7.4
    - php: 8.0
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - pecl channel-update pecl.php.net
  - pecl install ast
  - |
    if [ $TRAVIS_PHP_VERSION == '7.4' ]; then
      printf "\n" | pecl install imagick;
    fi

install:
  - composer install --no-interaction --prefer-source
  - composer validate

script:
  - vendor/bin/phpunit --configuration phpunit.xml
  - vendor/bin/phan

after_script: bash <(curl -s https://codecov.io/bash)
