addons:
  apt:
    packages:
      - imagemagick

language: php

env:
  global:
    - PHAN_ALLOW_XDEBUG=0 PHAN_DISABLE_XDEBUG_WARN=1

matrix:
  include:
    - php: 7.4

before_install:
  - pecl channel-update pecl.php.net
  - printf "\n" | pecl install imagick
  - pecl install ast

install:
  - composer install --no-interaction --prefer-source
  - composer validate

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
  - vendor/bin/phan

after_script: bash <(curl -s https://codecov.io/bash)
