# from https://github.com/PHPMailer/PHPMailer

on:
  push:
    branches:
      - main

name: "Docs"

jobs:
  build_and_publish:
    name: "Build and publish Docs"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: "Build Docs"
        uses: ./.github/actions/build-docs

      - name: "Publish Docs to gh-pages"
        uses: JamesIves/github-pages-deploy-action@4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
